//Structure: [x, y, type, Planet, System, Sector, link to WookCanon, Name to show]
const pointsOfInterest = [
  [843, 597, "Planet", "Alderaan", "Alderaan", "Alderaan", "Republic", "https://starwars.fandom.com/wiki/Alderaan", "Alderaan", true],
  [737, 120, "Planet", "Asation", "Asation", "Veragi", "Gree Enclave", "https://starwars.fandom.com/wiki/Asation", "Asation", false],
  [1175, 352, "Planet", "Auratera", "Auratera", "Vorzyd", "Disputed", "https://starwars.fandom.com/wiki/Auratera", "Auratera", true],
  [883, 633, "Planet", "Balmorra", "Balmorra", , "Republic", "https://starwars.fandom.com/wiki/Balmorra", "Balmorra", true],
  [764, 587, "Planet", "Brentaal IV", "Brentaal", "Bormea", "Republic", "https://starwars.fandom.com/wiki/Brentaal_IV", "Brentaal", true],
  [883, 633, "Planet", "Balmorra", "Balmorra", , "Republic", "https://starwars.fandom.com/wiki/Balmorra", "Balmorra", true],
  [819, 340, "Planet", "Cademimu V", "Cademimu", "Cademimu", "Republic", "https://starwars.fandom.com/wiki/Cademimu_V", "Cademimu", false],
  [929, 338, "Planet", "Cathar", "Cathar", "Quelli", , "https://starwars.fandom.com/wiki/Cathar_(planet)", "Cathar", false],
  [362, 569, "Planet", "Copero", "Copero", , "Chiss Ascendancy", "https://starwars.fandom.com/wiki/Copero", "Copero", true],
  [861, 720, "Planet", "Corellia", "Corellia", "Corellian", "Republic", "https://starwars.fandom.com/wiki/Corellia", "Corellia", true],
  [754, 592, "Planet", "Coruscant", "Coruscant", "Corusca", "Republic", "https://starwars.fandom.com/wiki/Coruscant", "Coruscant", true],
  [347, 511, "Planet", "Csilla", "Csilla", , "Chiss Ascendancy", "https://starwars.fandom.com/wiki/Csilla", "Csilla", true],
  [753, 208, "Planet", "Dantooine", "Dantooine", "Raioballo", "Independent", "https://starwars.fandom.com/wiki/Dantooine", "Dantooine", true],
  [969, 346, "Planet", "Dathomir", "Dathomir", "Quelli", "Independent", "https://starwars.fandom.com/wiki/Dathomir", "Dathomir", true],
  [932, 424, "Planet", "Denova", "Denova", "Ojoster", "Independent", "https://starwars.fandom.com/wiki/Denova", "Denova", false],
  [863, 727, "Planet", "Duro", "Duro", "Duro", "Republic", "https://starwars.fandom.com/wiki/Duro", "Duro", true],
  [1198, 261, "Planet", "Dromund Fels", "Dromund", "Esstran", "Empire", "https://starwars.fandom.com/wiki/Dromund_Fels", "Dromund Fels", false],
  [1186, 262, "Planet", "Dromund Kaas", "Dromund", "Esstran", "Empire", "https://starwars.fandom.com/wiki/Dromund_Kaas", "Dromund Kaas", true],
  [1184, 305, "Planet", "Elom", "Elom", "Sertar", "Disputed", "https://starwars.fandom.com/wiki/Elom_(planet)", "Elom", true],
  [861, 1160, "Planet", "Eriadu", "Eriadu", "Seswenna", "Republic", "https://starwars.fandom.com/wiki/Eriadu", "Eriadu", true],
  [1218, 334, "Planet", "Felucia", "Felucia", "Thanium Worlds", "Independent", "https://starwars.fandom.com/wiki/Felucia", "Felucia", true],
  [779, 690, , , , , , , "Galactic Centre", true],
  [1346, 473, "Planet", "Gand", "Gand", "Shadola", "Independent", "https://starwars.fandom.com/wiki/Gand_(planet)", "Gand", true],
  [1185, 1064, "Planet", "Geonosis", "Geonosis", "Arkanis", "Independent", "https://starwars.fandom.com/wiki/Geonosis", "Geonosis", true],
  [1330, 888, "Planet", "Gamor", "Gamor", "Chaykin", , "https://starwars.fandom.com/wiki/Gamor", "Gamor", false],
  [757, 110, "Planet", "Gree", "Gree", "Veragi", "Gree Enclave", "https://starwars.fandom.com/wiki/Gree", "Gree", true],
  [689, 1181, "Planet", "Hoth", "Hoth", "Anoat", "Independent", "https://starwars.fandom.com/wiki/Hoth", "Hoth", true],
  [1234, 734, "Planet", "Nal Hutta", "Y'Toub", , "Hutt Space", "https://starwars.fandom.com/wiki/Nal_Hutta", "Hutta", true],
  [471, 424, "Planet", "Ilum", "Ilum", "7G Sector", "Contested", "https://starwars.fandom.com/wiki/Ilum", "Ilum", true],
  [1221, 271, "Space Station", "Vaiken Spacedock", , , "Empire", "https://starwars.fandom.com/wiki/Vaiken_Spacedock", "Imperial Fleet", false],
  [642, 208, "Planet", "Kalee", "Kalee", , "Independent", "https://starwars.fandom.com/wiki/Kalee", "Kalee", true],
  [1078, 585, "Planet", "Kashyyyk", "Kashyyyk", "Mytaranor", "Republic", "https://starwars.fandom.com/wiki/Kashyyyk", "Kashyyyk", true],
  [1293, 1006, "Planet", "Kowak", "Kowak", "Sevetta", "Independent", "https://starwars.fandom.com/wiki/Kowak", "Kowak", true ],
  [1175, 276, "Planet", "Korriban", "Horuset", "Esstran", "Empire", "https://starwars.fandom.com/wiki/Korriban", "Korriban", true],
  [883, 633, "Planet", "Kuat", "Kuat", "Kuat", "Republic", "https://starwars.fandom.com/wiki/Kuat", "Kuat", true],
  [901, 985, "Planet", "M'haeli", "Plynn", "Majoor", "Republic", "https://starwars.fandom.com/wiki/M%27haeli", "M'haeli", true],
  [1249, 230, "Planet", "Malachor V", "Malachor", "Chorlian", "Empire", "https://starwars.fandom.com/wiki/Malachor_V", "Malachor", false],
  [972, 690, "Planet", "Manaan", "Pyrshak", , "Independent", "https://starwars.fandom.com/wiki/Manaan", "Manaan", true],
  [1003, 407, "Planet", "Mandalore", "Mandalore", "Mandalore", "Independent", "https://starwars.fandom.com/wiki/Mandalore", "Mandalore", true],
  [1134, 489, "Space station", "Mek-Sha", , , "Independent", "https://starwars.fandom.com/wiki/Mek-Sha", "Mek-Sha", false],
  [983, 1075, "Planet", "Naboo", "Naboo", "Chommell", "Independent", "https://starwars.fandom.com/wiki/Naboo", "Naboo", true],
  [1236, 736, "Moon", "Nar Shaddaa", "Y'Toub", "Hutt Space", "Hutt Space", "https://starwars.fandom.com/wiki/Nar_Shaddaa", "Nar Shaddaa", true],
  [880, 637, "Planet", "Pure Neimodia", "Neimodia", , "Republic", "https://starwars.fandom.com/wiki/Neimodia", "Neimodia", true],
  [239, 869, "Planet", "Odessen", , , "Independent", "https://starwars.fandom.com/wiki/Odessen", "Odessen", false],
  [1008, 581, "Planet", "Onderon", "Japrael", "Japrael", "Disputed", "https://starwars.fandom.com/wiki/Onderon", "Onderon", true],
  [756, 418, "Planet", "Ord Mantell", "Bright Jewel", "Bright Jewel", "Republic", "https://starwars.fandom.com/wiki/Ord_Mantell", "Ord Mantell", true],
  [1048, 148, "Moon", "Oricon", "Oricon", "Corva", "Empire", "https://starwars.fandom.com/wiki/Oricon", "Oricon", false],
  [1230, 375, "Planet", "Ossus", "Adega", "Auril", "Disputed", "https://starwars.fandom.com/wiki/Ossus", "Ossus", true],
  [1294, 655, "Planet", "Quesh", "Quesh", , "Disputed", "https://starwars.fandom.com/wiki/Quesh", "Quesh", false],
  [439, 716, "Planet", "Rakata Prime", "Lehon", , "Independent", "https://starwars.fandom.com/wiki/Rakata_Prime", "Rakata Prime", true],
  [500, 1010, "Planet", "Rattatak", "Guter Wade", "Trilon", "Independent", "https://starwars.fandom.com/wiki/Rattatak  ", "Rattatak", true],
  [689, 623, "Space Station", "Carrick Station", , , "Republic", "https://starwars.fandom.com/wiki/Carrick_Station", "Republic Fleet", false],
  [1246, 948, "Planet", "Rishi", "Rishi", "Abrion", "Independent", "https://starwars.fandom.com/wiki/Rishi", "Rishi", true],
  [1166, 1046, "Planet", "Rodia", "Tyrius", "Savareen", "Republic", "https://starwars.fandom.com/wiki/Rodia", "Rodia", true],
  [1032, 278, "Planet", "Serenno", "Serenno", "D'Astan", "Empire", "https://starwars.fandom.com/wiki/Serenno", "Serenno", true],
  [859, 1126, "Planet", "Sullust", "Sullust", "Brema", "Republic", "https://starwars.fandom.com/wiki/Sullust", "Sulliust", true],
  [939, 395, "Planet", "Taris", "Taris", "Ojoster", "Empire", "https://starwars.fandom.com/wiki/Zeltros", "Taris", true],
  [1188, 1055, "Planet", "Tatooine", "Tatoo", "Arkanis", "Independent", "https://starwars.fandom.com/wiki/Tatooine", "Tatooine", true],
  [1389, 402, "Planet", "Taral V", "Taral", "Calamari", "Empire", "https://starwars.fandom.com/wiki/Taral_V", "Taral V", false],
  [1081, 583, "Planet", "Trandosha", "Kashyyyk", "Mytaranor", "Republic", "https://starwars.fandom.com/wiki/Trandosha", "Trandosha", true],
  [754, 646, "Planet", "Tython", "Tython", "Sector 5", "Republic", "https://starwars.fandom.com/wiki/Tython", "Tython", true],
  [1159, 637, "Planet", "Ubrikkia", "Ubrikkia", "Kastolar", "Hutt Space", "https://starwars.fandom.com/wiki/Ubrikkia", "Ubrikkia", true],
  [1033, 606, "Planet", "Umbara", "Umbara", "Ghost Nebula", "Independent", "https://starwars.fandom.com/wiki/Umbara", "Umbara", true],
  [1188, 231, "Planet", "Upekzar", "Upekzar", "Esstran", "Empire", "https://starwars.fandom.com/wiki/Upekzar", "Upekzar", false],
  [1268, 348, "Planet", "Voss", "Voss", "Allied Tion", "Independent", "https://starwars.fandom.com/wiki/Voss", "Voss", false],
  [1080, 584, "Moon", "Wasskah", "Kashyyyk", "Mytaranor", "Republic", "https://starwars.fandom.com/wiki/Wasskah", "Wasskah", true],
  [1067, 320, "Moon", "Yavin IV", "Yavin", "Gordian", , "https://starwars.fandom.com/wiki/Yavin_4", "Yavin", true],
  [777, 471, "Planet", "Yinchorr", "Yinchorri", "Fellwe", "Independent", "https://starwars.fandom.com/wiki/Yinchorr  ", "Yinchorr", true],
  [15, 825, "Planet", "Zakuul", , , "Zakuul", "https://starwars.fandom.com/wiki/Zakuul", "Zakuul", false],
  [995, 639, "Planet", "Zeltros", "Zel", , "Republic", "https://starwars.fandom.com/wiki/Zeltros", "Zeltros", true],
  [1172, 240, "Planet", "Ziost", "Ziost", "Esstran", "Empire", "https://starwars.fandom.com/wiki/Ziost", "Ziost", true]
];

export default pointsOfInterest;